### PR TITLE
Proposed directory structure of this new repo

### PR DESCRIPTION
**Pull request by oybed**
@sabre1041 @makentenza FYI - proposal for directory structure 

```
|- openshift
|- openstack
|- 3rd-party
|   |- dynatrace
|   |   |- openshift
|   |   |   |- templates
|   |   |   |- params
|   |- sysdig
|   |   |- openshift
|   |   |   |- templates
|   |   |   |- params
  :
```

### CODE REVIEW

**Comment by makentenza** [comment]
@oybed As RH will probably never has a solution for this (even we support Prometheus is still 3rd party) I should remove the 3rd-party directory from that structure

**Comment by makentenza** [comment]
I'd suggest one of the following structures:

Red Hat Product based
-------------------------------
```
|- openshift
|  |- prometheus
|  |  |- templates
|  |  |- params
|  |- dynatrace
|  |  |- templates
|  |  |- params
|  |- sysdig
|  |  |- templates
|  |  |- params
|- openstack
|  |- prometheus
|  |  |- templates
|  |  |- params
|  |- dynatrace
|  |  |- templates
|  |  |- params
|  |- sysdig
|  |  |- templates
|  |  |- params
|- rhev
|  |- prometheus
|  |  |- templates
|  |  |- params
|  |- dynatrace
|  |  |- templates
|  |  |- params
|  |- sysdig
|  |  |- templates
|  |  |- params
```

Monitoring Tech based
------------------------------
```
|- prometheus
|  |- openshift
|  |  |- templates
|  |  |- params
|  |- openstack
|  |  |- templates
|  |  |- params
|  |- rhev
|  |  |- templates
|  |  |- params
|- dynatrace
|  |- openshift
|  |  |- templates
|  |  |- params
|  |- openstack
|  |  |- templates
|  |  |- params
|  |- rhev
|  |  |- templates
|  |  |- params
|- sysdig
|  |- openshift
|  |  |- templates
|  |  |- params
|  |- openstack
|  |  |- templates
|  |  |- params
|  |- rhev
|  |  |- templates
|  |  |- params
```

**Comment by makentenza** [comment]
@oybed @etsauer @sabre1041 just updated with alternative structures

**Comment by sabre1041** [comment]
@makentenza I would favor a monitoring based structured approach

**Comment by makentenza** [comment]
Agree @sabre1041, I think it makes more sense here as the repository name is 'monitoring' and the first view for a user checking the repository should be these different monitoring tools

**Comment by makentenza** [comment]
@oybed @sabre1041 I'll add the new structure as part of the open PR #1. Is that ok?

**Comment by oybed** [comment]
@makentenza I'll update this PR and we can get it merged before your PR goes in.

**Review by makentenza — APPROVED** [review]
LGTM

**Pull request merged**
